name: Build and publish era-watchdog image

on:
  push:
    branches: ["main", "develop"]
    tags:
      - "*"
  pull_request:
    branches:
      - "main"

jobs:
  push_to_registry:
    name: Build and push Docker image
    runs-on: [matterlabs-ci-runner]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate build ID for Flux Image Automation
        id: tag
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        run: |
          echo "::set-output name=BUILD_ID::${GITHUB_REF#refs/*/}"
      - name: Generate build ID for Flux Image Automation
        id: build
        if: ${{ !startsWith(github.ref, 'refs/tags') }}
        run: |
          sha=$(git rev-parse --short HEAD)
          ts=$(date +%s%N | cut -b1-13)
          echo "::set-output name=BUILD_ID::${sha}-${ts}"
      - name: Auth to google artifact registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev -q

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        with:
          push: true
          tags: |
            "us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/era-watchdog:latest"
            "us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/era-watchdog:${{ steps.tag.outputs.BUILD_ID }}"
          file: Dockerfile
          no-cache: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        if: ${{ !startsWith(github.ref, 'refs/tags') }}
        with:
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            "us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/era-watchdog:latest"
            "us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/era-watchdog:${{ steps.build.outputs.BUILD_ID }}"
          file: Dockerfile
          no-cache: true
