name: Build and push Docker image
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-push-image:
    name: Build and push Docker image
    env:
      image_tag: ${{ inputs.image_tag }}
    runs-on: [self-hosted, ci-runner]
    steps:
      - uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Login to GAR
        run: |
          gcloud auth configure-docker us-docker.pkg.dev -q
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v4
        with:
          push: ${{ !github.event.issue.pull_request }}
          tags: |
            us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/era-watchdog:${{ steps.vars.outputs.sha_short }}
            us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/era-watchdog:latest
      - name: Build and push on git tag
        id: docker_build_push_tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v4
        with:
          push: ${{ !github.event.issue.pull_request }}
          tags: |
            us-docker.pkg.dev/matterlabs-infra/matterlabs-docker/era-watchdog:${{ github.ref_name }}
      - name: Print image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
